import { v4 as uuidv4 } from "uuid";

const products = [
	{
		id: uuidv4(),
		name: "Davidoff Espresso 57",
		price: 12.99,
		rating: 4.8,
		discount: 10,
		company: "Davidoff",
		imgSrc: "https://example.com/davidoff-espresso-57.jpg",
	},
	{
		id: uuidv4(),
		name: "Davidoff Fine Aroma Coffee",
		price: 10.99,
		rating: 4.5,
		discount: 5,
		company: "Davidoff",
		imgSrc: "https://example.com/davidoff-fine-aroma.jpg",
	},
	{
		id: uuidv4(),
		name: "Davidoff Rich Aroma Coffee",
		price: 11.49,
		rating: 4.7,
		discount: 15,
		company: "Davidoff",
		imgSrc: "https://example.com/davidoff-rich-aroma.jpg",
	},
	{
		id: uuidv4(),
		name: "Nike Phantom GT2 Elite Football Boots",
		price: 249.99,
		rating: 4.9,
		discount: 20,
		company: "Nike",
		imgSrc: "https://example.com/nike-phantom-gt2-elite.jpg",
	},
	{
		id: uuidv4(),
		name: "Nike Flight Premier League Football",
		price: 129.99,
		rating: 4.6,
		discount: 10,
		company: "Nike",
		imgSrc: "https://example.com/nike-flight-premier-league.jpg",
	},
	{
		id: uuidv4(),
		name: "Nike Strike Team Football",
		price: 39.99,
		rating: 4.3,
		discount: 8,
		company: "Nike",
		imgSrc: "https://example.com/nike-strike-team.jpg",
	},
	{
		id: uuidv4(),
		name: "Davidoff Café Crème Intense",
		price: 14.99,
		rating: 4.9,
		discount: 12,
		company: "Davidoff",
		imgSrc: "https://example.com/davidoff-creme-intense.jpg",
	},
	{
		id: uuidv4(),
		name: "Nike Academy Team Football",
		price: 25.99,
		rating: 4.4,
		discount: 5,
		company: "Nike",
		imgSrc: "https://example.com/nike-academy-team.jpg",
	},
	{
		id: uuidv4(),
		name: "Nike Mercurial Superfly 8 Elite",
		price: 269.99,
		rating: 4.8,
		discount: 25,
		company: "Nike",
		imgSrc: "https://example.com/nike-mercurial-superfly-8-elite.jpg",
	},
	{
		id: uuidv4(),
		name: "Davidoff Café Grande Cuvée",
		price: 15.99,
		rating: 4.7,
		discount: 10,
		company: "Davidoff",
		imgSrc: "https://example.com/davidoff-grande-cuvee.jpg",
	},
];

export { products };
